// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/logic/user"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/svc"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) CreateUser(ctx context.Context, in *pb.CreateUserReq) (*pb.BaseResp, error) {
	l := userlogic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServer) BatchCreateUsers(ctx context.Context, in *pb.BatchCreateUserReq) (*pb.IDsResp, error) {
	l := userlogic.NewBatchCreateUsersLogic(ctx, s.svcCtx)
	return l.BatchCreateUsers(in)
}

func (s *UserServer) DeleteUser(ctx context.Context, in *pb.IDReq) (*pb.BaseResp, error) {
	l := userlogic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

func (s *UserServer) BatchDeleteUser(ctx context.Context, in *pb.IDsResp) (*pb.BaseResp, error) {
	l := userlogic.NewBatchDeleteUserLogic(ctx, s.svcCtx)
	return l.BatchDeleteUser(in)
}

func (s *UserServer) UpdateProfile(ctx context.Context, in *pb.UpdateProfileReq) (*pb.BaseResp, error) {
	l := userlogic.NewUpdateProfileLogic(ctx, s.svcCtx)
	return l.UpdateProfile(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *pb.IDReq) (*pb.UserInfoResp, error) {
	l := userlogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) GetUserList(ctx context.Context, in *pb.PageInfoReq) (*pb.UserListResp, error) {
	l := userlogic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}

func (s *UserServer) UpdateUserStatus(ctx context.Context, in *pb.StatusCodeReq) (*pb.BaseResp, error) {
	l := userlogic.NewUpdateUserStatusLogic(ctx, s.svcCtx)
	return l.UpdateUserStatus(in)
}

func (s *UserServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) ChangePassword(ctx context.Context, in *pb.ChangePasswdReq) (*pb.BaseResp, error) {
	l := userlogic.NewChangePasswordLogic(ctx, s.svcCtx)
	return l.ChangePassword(in)
}
