// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/logic/api"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/svc"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/pb"
)

type ApiServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedApiServer
}

func NewApiServer(svcCtx *svc.ServiceContext) *ApiServer {
	return &ApiServer{
		svcCtx: svcCtx,
	}
}

func (s *ApiServer) CreateApi(ctx context.Context, in *pb.CreateApiReq) (*pb.BaseResp, error) {
	l := apilogic.NewCreateApiLogic(ctx, s.svcCtx)
	return l.CreateApi(in)
}

func (s *ApiServer) DeleteApi(ctx context.Context, in *pb.IDReq) (*pb.BaseResp, error) {
	l := apilogic.NewDeleteApiLogic(ctx, s.svcCtx)
	return l.DeleteApi(in)
}

func (s *ApiServer) UpdateApi(ctx context.Context, in *pb.UpdateApiReq) (*pb.BaseResp, error) {
	l := apilogic.NewUpdateApiLogic(ctx, s.svcCtx)
	return l.UpdateApi(in)
}

func (s *ApiServer) GetApi(ctx context.Context, in *pb.IDReq) (*pb.GetApiResp, error) {
	l := apilogic.NewGetApiLogic(ctx, s.svcCtx)
	return l.GetApi(in)
}

func (s *ApiServer) GetApiListByMenu(ctx context.Context, in *pb.IDReq) (*pb.GetApiListResp, error) {
	l := apilogic.NewGetApiListByMenuLogic(ctx, s.svcCtx)
	return l.GetApiListByMenu(in)
}
