// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/logic/api"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/svc"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/pb"
)

type ApiServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedApiServer
}

func NewApiServer(svcCtx *svc.ServiceContext) *ApiServer {
	return &ApiServer{
		svcCtx: svcCtx,
	}
}

func (s *ApiServer) CreateOrUpdateApi(ctx context.Context, in *pb.ApiInfo) (*pb.BaseResp, error) {
	l := apilogic.NewCreateOrUpdateApiLogic(ctx, s.svcCtx)
	return l.CreateOrUpdateApi(in)
}

func (s *ApiServer) DeleteApi(ctx context.Context, in *pb.IDReq) (*pb.BaseResp, error) {
	l := apilogic.NewDeleteApiLogic(ctx, s.svcCtx)
	return l.DeleteApi(in)
}

func (s *ApiServer) GetApiList(ctx context.Context, in *pb.ApiPageReq) (*pb.ApiListResp, error) {
	l := apilogic.NewGetApiListLogic(ctx, s.svcCtx)
	return l.GetApiList(in)
}
