// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package server

import (
	"context"

	"backend/rabbit-go/usercenter/rpc/internal/logic/auth"
	"backend/rabbit-go/usercenter/rpc/internal/svc"
	"backend/rabbit-go/usercenter/rpc/pb"
)

type AuthServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedAuthServer
}

func NewAuthServer(svcCtx *svc.ServiceContext) *AuthServer {
	return &AuthServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServer) GetMenuAuthority(ctx context.Context, in *pb.IDReq) (*pb.RoleMenuAuthorityResp, error) {
	l := authlogic.NewGetMenuAuthorityLogic(ctx, s.svcCtx)
	return l.GetMenuAuthority(in)
}

func (s *AuthServer) CreateOrUpdateMenuAuthority(ctx context.Context, in *pb.RoleMenuAuthorityReq) (*pb.BaseResp, error) {
	l := authlogic.NewCreateOrUpdateMenuAuthorityLogic(ctx, s.svcCtx)
	return l.CreateOrUpdateMenuAuthority(in)
}
