// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package client

import (
	"context"

	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApiInfo               = pb.ApiInfo
	BaseResp              = pb.BaseResp
	BatchCreateUserReq    = pb.BatchCreateUserReq
	ChangeDept            = pb.ChangeDept
	ChangePasswdReq       = pb.ChangePasswdReq
	ChangePositionReq     = pb.ChangePositionReq
	CreateApiReq          = pb.CreateApiReq
	CreateMenuParamReq    = pb.CreateMenuParamReq
	CreateMenuReq         = pb.CreateMenuReq
	CreateRoleReq         = pb.CreateRoleReq
	CreateStationReq      = pb.CreateStationReq
	CreateTenantReq       = pb.CreateTenantReq
	CreateTokenReq        = pb.CreateTokenReq
	CreateUserReq         = pb.CreateUserReq
	Empty                 = pb.Empty
	GetApiListResp        = pb.GetApiListResp
	GetApiResp            = pb.GetApiResp
	GetMenuListReq        = pb.GetMenuListReq
	GetMenuListResp       = pb.GetMenuListResp
	GetParamsByMenuResp   = pb.GetParamsByMenuResp
	GetRoleResp           = pb.GetRoleResp
	GetStationByUserResp  = pb.GetStationByUserResp
	GetStationListResp    = pb.GetStationListResp
	GetStationResp        = pb.GetStationResp
	GetTeantListResp      = pb.GetTeantListResp
	GetTenantResp         = pb.GetTenantResp
	GetTokenListReq       = pb.GetTokenListReq
	GetTokenListResp      = pb.GetTokenListResp
	GetTokenResp          = pb.GetTokenResp
	GrantApiToRoleReq     = pb.GrantApiToRoleReq
	GrantMenuToRoleReq    = pb.GrantMenuToRoleReq
	GrantMenusToRoleReq   = pb.GrantMenusToRoleReq
	GrantRoleReq          = pb.GrantRoleReq
	GrantRoleToStationReq = pb.GrantRoleToStationReq
	IDReq                 = pb.IDReq
	IDResp                = pb.IDResp
	IDsReq                = pb.IDsReq
	IDsResp               = pb.IDsResp
	LoginReq              = pb.LoginReq
	LoginResp             = pb.LoginResp
	MenuInfo              = pb.MenuInfo
	MenuParamInfo         = pb.MenuParamInfo
	Meta                  = pb.Meta
	PageInfoReq           = pb.PageInfoReq
	ReplaceUserReq        = pb.ReplaceUserReq
	RoleInfo              = pb.RoleInfo
	RoleListResp          = pb.RoleListResp
	StationInfo           = pb.StationInfo
	StationUserReq        = pb.StationUserReq
	StatusCodeReq         = pb.StatusCodeReq
	TSRU                  = pb.TSRU
	TenantInfo            = pb.TenantInfo
	TokenInfo             = pb.TokenInfo
	UpdateApiReq          = pb.UpdateApiReq
	UpdateMenuParamsReq   = pb.UpdateMenuParamsReq
	UpdateMenuReq         = pb.UpdateMenuReq
	UpdatePeriodReq       = pb.UpdatePeriodReq
	UpdateProfileReq      = pb.UpdateProfileReq
	UpdateRoleReq         = pb.UpdateRoleReq
	UpdateStationReq      = pb.UpdateStationReq
	UpdateStatusReq       = pb.UpdateStatusReq
	UpdateTenantReq       = pb.UpdateTenantReq
	UserInfoResp          = pb.UserInfoResp
	UserListResp          = pb.UserListResp

	Station interface {
		CreateStation(ctx context.Context, in *CreateStationReq, opts ...grpc.CallOption) (*BaseResp, error)
		DeleteStation(ctx context.Context, in *IDResp, opts ...grpc.CallOption) (*BaseResp, error)
		GetStation(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*GetStationResp, error)
		GetStationByUser(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*GetStationByUserResp, error)
		UpdateStation(ctx context.Context, in *UpdateStationReq, opts ...grpc.CallOption) (*BaseResp, error)
		UpdateStationSort(ctx context.Context, in *ChangePositionReq, opts ...grpc.CallOption) (*BaseResp, error)
		UpdateDep(ctx context.Context, in *ChangeDept, opts ...grpc.CallOption) (*BaseResp, error)
		GrantRoleToStation(ctx context.Context, in *GrantRoleReq, opts ...grpc.CallOption) (*BaseResp, error)
		GrantStationToUser(ctx context.Context, in *StationUserReq, opts ...grpc.CallOption) (*BaseResp, error)
		ReplaceStationUser(ctx context.Context, in *ReplaceUserReq, opts ...grpc.CallOption) (*BaseResp, error)
		GetStationList(ctx context.Context, in *PageInfoReq, opts ...grpc.CallOption) (*GetStationListResp, error)
	}

	defaultStation struct {
		cli zrpc.Client
	}
)

func NewStation(cli zrpc.Client) Station {
	return &defaultStation{
		cli: cli,
	}
}

func (m *defaultStation) CreateStation(ctx context.Context, in *CreateStationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.CreateStation(ctx, in, opts...)
}

func (m *defaultStation) DeleteStation(ctx context.Context, in *IDResp, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.DeleteStation(ctx, in, opts...)
}

func (m *defaultStation) GetStation(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*GetStationResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.GetStation(ctx, in, opts...)
}

func (m *defaultStation) GetStationByUser(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*GetStationByUserResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.GetStationByUser(ctx, in, opts...)
}

func (m *defaultStation) UpdateStation(ctx context.Context, in *UpdateStationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.UpdateStation(ctx, in, opts...)
}

func (m *defaultStation) UpdateStationSort(ctx context.Context, in *ChangePositionReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.UpdateStationSort(ctx, in, opts...)
}

func (m *defaultStation) UpdateDep(ctx context.Context, in *ChangeDept, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.UpdateDep(ctx, in, opts...)
}

func (m *defaultStation) GrantRoleToStation(ctx context.Context, in *GrantRoleReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.GrantRoleToStation(ctx, in, opts...)
}

func (m *defaultStation) GrantStationToUser(ctx context.Context, in *StationUserReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.GrantStationToUser(ctx, in, opts...)
}

func (m *defaultStation) ReplaceStationUser(ctx context.Context, in *ReplaceUserReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.ReplaceStationUser(ctx, in, opts...)
}

func (m *defaultStation) GetStationList(ctx context.Context, in *PageInfoReq, opts ...grpc.CallOption) (*GetStationListResp, error) {
	client := pb.NewStationClient(m.cli.Conn())
	return client.GetStationList(ctx, in, opts...)
}
