// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package client

import (
	"context"

	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApiInfo               = pb.ApiInfo
	BaseResp              = pb.BaseResp
	BatchCreateUserReq    = pb.BatchCreateUserReq
	ChangeDept            = pb.ChangeDept
	ChangePasswdReq       = pb.ChangePasswdReq
	ChangePositionReq     = pb.ChangePositionReq
	CreateApiReq          = pb.CreateApiReq
	CreateMenuParamReq    = pb.CreateMenuParamReq
	CreateMenuReq         = pb.CreateMenuReq
	CreateRoleReq         = pb.CreateRoleReq
	CreateStationReq      = pb.CreateStationReq
	CreateTenantReq       = pb.CreateTenantReq
	CreateTokenReq        = pb.CreateTokenReq
	CreateUserReq         = pb.CreateUserReq
	Empty                 = pb.Empty
	GetApiListResp        = pb.GetApiListResp
	GetApiResp            = pb.GetApiResp
	GetMenuListReq        = pb.GetMenuListReq
	GetMenuListResp       = pb.GetMenuListResp
	GetParamsByMenuResp   = pb.GetParamsByMenuResp
	GetRoleResp           = pb.GetRoleResp
	GetStationByUserResp  = pb.GetStationByUserResp
	GetStationListResp    = pb.GetStationListResp
	GetStationResp        = pb.GetStationResp
	GetTeantListResp      = pb.GetTeantListResp
	GetTenantResp         = pb.GetTenantResp
	GetTokenListReq       = pb.GetTokenListReq
	GetTokenListResp      = pb.GetTokenListResp
	GetTokenResp          = pb.GetTokenResp
	GrantApiToRoleReq     = pb.GrantApiToRoleReq
	GrantMenuToRoleReq    = pb.GrantMenuToRoleReq
	GrantMenusToRoleReq   = pb.GrantMenusToRoleReq
	GrantRoleReq          = pb.GrantRoleReq
	GrantRoleToStationReq = pb.GrantRoleToStationReq
	IDReq                 = pb.IDReq
	IDResp                = pb.IDResp
	IDsReq                = pb.IDsReq
	IDsResp               = pb.IDsResp
	LoginReq              = pb.LoginReq
	LoginResp             = pb.LoginResp
	MenuInfo              = pb.MenuInfo
	MenuParamInfo         = pb.MenuParamInfo
	Meta                  = pb.Meta
	PageInfoReq           = pb.PageInfoReq
	ReplaceUserReq        = pb.ReplaceUserReq
	RoleInfo              = pb.RoleInfo
	RoleListResp          = pb.RoleListResp
	StationInfo           = pb.StationInfo
	StationUserReq        = pb.StationUserReq
	StatusCodeReq         = pb.StatusCodeReq
	TSRU                  = pb.TSRU
	TenantInfo            = pb.TenantInfo
	TokenInfo             = pb.TokenInfo
	UpdateApiReq          = pb.UpdateApiReq
	UpdateMenuParamsReq   = pb.UpdateMenuParamsReq
	UpdateMenuReq         = pb.UpdateMenuReq
	UpdatePeriodReq       = pb.UpdatePeriodReq
	UpdateProfileReq      = pb.UpdateProfileReq
	UpdateRoleReq         = pb.UpdateRoleReq
	UpdateStationReq      = pb.UpdateStationReq
	UpdateStatusReq       = pb.UpdateStatusReq
	UpdateTenantReq       = pb.UpdateTenantReq
	UserInfoResp          = pb.UserInfoResp
	UserListResp          = pb.UserListResp

	Role interface {
		CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*BaseResp, error)
		DeleteRole(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*BaseResp, error)
		UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*BaseResp, error)
		GetRole(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*GetRoleResp, error)
		GrantMenuToRole(ctx context.Context, in *GrantMenuToRoleReq, opts ...grpc.CallOption) (*BaseResp, error)
		GrantApiToRole(ctx context.Context, in *GrantApiToRoleReq, opts ...grpc.CallOption) (*BaseResp, error)
		GrantRoleToStation(ctx context.Context, in *GrantRoleToStationReq, opts ...grpc.CallOption) (*BaseResp, error)
		GetRoleList(ctx context.Context, in *PageInfoReq, opts ...grpc.CallOption) (*RoleListResp, error)
	}

	defaultRole struct {
		cli zrpc.Client
	}
)

func NewRole(cli zrpc.Client) Role {
	return &defaultRole{
		cli: cli,
	}
}

func (m *defaultRole) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultRole) DeleteRole(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultRole) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultRole) GetRole(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*GetRoleResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultRole) GrantMenuToRole(ctx context.Context, in *GrantMenuToRoleReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.GrantMenuToRole(ctx, in, opts...)
}

func (m *defaultRole) GrantApiToRole(ctx context.Context, in *GrantApiToRoleReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.GrantApiToRole(ctx, in, opts...)
}

func (m *defaultRole) GrantRoleToStation(ctx context.Context, in *GrantRoleToStationReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.GrantRoleToStation(ctx, in, opts...)
}

func (m *defaultRole) GetRoleList(ctx context.Context, in *PageInfoReq, opts ...grpc.CallOption) (*RoleListResp, error) {
	client := pb.NewRoleClient(m.cli.Conn())
	return client.GetRoleList(ctx, in, opts...)
}
