// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/logic/init"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/svc"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/pb"
)

type InitServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInitServer
}

func NewInitServer(svcCtx *svc.ServiceContext) *InitServer {
	return &InitServer{
		svcCtx: svcCtx,
	}
}

func (s *InitServer) InitDatabase(ctx context.Context, in *pb.Empty) (*pb.BaseResp, error) {
	l := initlogic.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
