// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "github.com/zhuangpeng/rabbit-go/usercenter/api/internal/handler/user"
	"github.com/zhuangpeng/rabbit-go/usercenter/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
	)
}
