// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/logic/station"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/svc"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/pb"
)

type StationServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStationServer
}

func NewStationServer(svcCtx *svc.ServiceContext) *StationServer {
	return &StationServer{
		svcCtx: svcCtx,
	}
}

func (s *StationServer) CreateStation(ctx context.Context, in *pb.CreateStationReq) (*pb.BaseResp, error) {
	l := stationlogic.NewCreateStationLogic(ctx, s.svcCtx)
	return l.CreateStation(in)
}

func (s *StationServer) DeleteStation(ctx context.Context, in *pb.IDResp) (*pb.BaseResp, error) {
	l := stationlogic.NewDeleteStationLogic(ctx, s.svcCtx)
	return l.DeleteStation(in)
}

func (s *StationServer) GetStation(ctx context.Context, in *pb.IDReq) (*pb.GetStationResp, error) {
	l := stationlogic.NewGetStationLogic(ctx, s.svcCtx)
	return l.GetStation(in)
}

func (s *StationServer) GetStationByUser(ctx context.Context, in *pb.IDReq) (*pb.GetStationByUserResp, error) {
	l := stationlogic.NewGetStationByUserLogic(ctx, s.svcCtx)
	return l.GetStationByUser(in)
}

func (s *StationServer) UpdateStation(ctx context.Context, in *pb.UpdateStationReq) (*pb.BaseResp, error) {
	l := stationlogic.NewUpdateStationLogic(ctx, s.svcCtx)
	return l.UpdateStation(in)
}

func (s *StationServer) UpdateStationSort(ctx context.Context, in *pb.ChangePositionReq) (*pb.BaseResp, error) {
	l := stationlogic.NewUpdateStationSortLogic(ctx, s.svcCtx)
	return l.UpdateStationSort(in)
}

func (s *StationServer) UpdateDep(ctx context.Context, in *pb.ChangeDept) (*pb.BaseResp, error) {
	l := stationlogic.NewUpdateDepLogic(ctx, s.svcCtx)
	return l.UpdateDep(in)
}

func (s *StationServer) GrantRoleToStation(ctx context.Context, in *pb.GrantRoleReq) (*pb.BaseResp, error) {
	l := stationlogic.NewGrantRoleToStationLogic(ctx, s.svcCtx)
	return l.GrantRoleToStation(in)
}

func (s *StationServer) GrantStationToUser(ctx context.Context, in *pb.StationUserReq) (*pb.BaseResp, error) {
	l := stationlogic.NewGrantStationToUserLogic(ctx, s.svcCtx)
	return l.GrantStationToUser(in)
}

func (s *StationServer) ReplaceStationUser(ctx context.Context, in *pb.ReplaceUserReq) (*pb.BaseResp, error) {
	l := stationlogic.NewReplaceStationUserLogic(ctx, s.svcCtx)
	return l.ReplaceStationUser(in)
}

func (s *StationServer) GetStationList(ctx context.Context, in *pb.PageInfoReq) (*pb.GetStationListResp, error) {
	l := stationlogic.NewGetStationListLogic(ctx, s.svcCtx)
	return l.GetStationList(in)
}
