// Code generated by goctl. DO NOT EDIT!
// Source: usercenter.proto

package server

import (
	"context"

	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/logic/menu"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/internal/svc"
	"github.com/zhuangpeng/rabbit-go/usercenter/rpc/pb"
)

type MenuServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMenuServer
}

func NewMenuServer(svcCtx *svc.ServiceContext) *MenuServer {
	return &MenuServer{
		svcCtx: svcCtx,
	}
}

func (s *MenuServer) CreateMenu(ctx context.Context, in *pb.CreateMenuReq) (*pb.BaseResp, error) {
	l := menulogic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

func (s *MenuServer) UpdateMenu(ctx context.Context, in *pb.UpdateMenuReq) (*pb.BaseResp, error) {
	l := menulogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *MenuServer) DeleteMenu(ctx context.Context, in *pb.IDReq) (*pb.BaseResp, error) {
	l := menulogic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

func (s *MenuServer) CreateMenuParam(ctx context.Context, in *pb.CreateMenuParamReq) (*pb.BaseResp, error) {
	l := menulogic.NewCreateMenuParamLogic(ctx, s.svcCtx)
	return l.CreateMenuParam(in)
}

func (s *MenuServer) DeleteParams(ctx context.Context, in *pb.IDReq) (*pb.BaseResp, error) {
	l := menulogic.NewDeleteParamsLogic(ctx, s.svcCtx)
	return l.DeleteParams(in)
}

func (s *MenuServer) GetMenuList(ctx context.Context, in *pb.GetMenuListReq) (*pb.GetMenuListResp, error) {
	l := menulogic.NewGetMenuListLogic(ctx, s.svcCtx)
	return l.GetMenuList(in)
}

func (s *MenuServer) GetParamsByMenu(ctx context.Context, in *pb.IDReq) (*pb.GetParamsByMenuResp, error) {
	l := menulogic.NewGetParamsByMenuLogic(ctx, s.svcCtx)
	return l.GetParamsByMenu(in)
}

func (s *MenuServer) UpdateMenuParams(ctx context.Context, in *pb.UpdateMenuParamsReq) (*pb.BaseResp, error) {
	l := menulogic.NewUpdateMenuParamsLogic(ctx, s.svcCtx)
	return l.UpdateMenuParams(in)
}
